# Generated by Django 4.2.5 on 2023-10-03 03:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticlePost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=500)),
                ("body", models.TextField()),
                (
                    "created",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 10, 3, 3, 18, 56, 779507, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_column",
                        to="article.articlecolumn",
                    ),
                ),
            ],
            options={
                "ordering": ("title",),
                "index_together": {("id", "slug")},
            },
        ),
    ]
