# Generated by Django 4.2.5 on 2023-10-04 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0002_articlepost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepost",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 4, 7, 1, 33, 603761, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
