# Generated by Django 4.2.5 on 2023-10-04 07:17

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("article", "0003_alter_articlepost_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepost",
            name="users_like",
            field=models.ManyToManyField(
                blank=True, related_name="articles_like", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="articlepost",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 4, 7, 17, 28, 500718, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
