# Generated by Django 4.2.5 on 2023-10-05 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0006_alter_articlepost_created_articletag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepost",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 5, 10, 6, 29, 367254, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
