# Generated by Django 4.2.5 on 2023-10-06 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0010_alter_articlepost_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepost",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 6, 6, 45, 46, 748747, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
