# Generated by Django 4.2.5 on 2023-09-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_userinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="photo",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
