# Generated by Django 4.2.5 on 2023-09-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_userinfo_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="photo",
            field=models.ImageField(blank=True, max_length=500, upload_to=""),
        ),
    ]
