# Generated by Django 4.2.5 on 2023-10-06 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0002_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="student",
            field=models.ManyToManyField(
                blank=True, related_name="courses_joined", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
