# Generated by Django 4.2.5 on 2023-09-24 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticles",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 24, 9, 28, 6, 883332, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
