# Generated by Django 4.2.5 on 2023-09-25 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_blogarticles_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticles",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 25, 9, 14, 39, 474463, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
