# Generated by Django 4.2.5 on 2023-09-27 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_blogarticles_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticles",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 27, 12, 5, 42, 37445, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
