# Generated by Django 4.2.5 on 2023-09-28 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_alter_blogarticles_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticles",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 28, 3, 9, 34, 799653, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
