# Generated by Django 4.2.5 on 2023-10-03 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_alter_blogarticles_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticles",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 3, 3, 18, 56, 762479, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
