# Generated by Django 4.2.5 on 2023-10-04 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_alter_blogarticles_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticles",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 4, 7, 1, 33, 588471, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
