# Generated by Django 4.2.5 on 2023-10-04 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_alter_blogarticles_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticles",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 4, 9, 15, 46, 21823, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
