# Generated by Django 4.2.5 on 2023-10-05 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_alter_blogarticles_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticles",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 5, 8, 23, 26, 567266, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
