# Generated by Django 4.2.5 on 2023-10-05 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0013_alter_blogarticles_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticles",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 5, 10, 6, 29, 350638, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
