# Generated by Django 4.2.5 on 2023-10-06 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0017_alter_blogarticles_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticles",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 6, 6, 45, 46, 732667, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
