# Generated by Django 4.2.5 on 2023-10-06 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0018_alter_blogarticles_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticles",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 6, 7, 51, 58, 784428, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
